# Generated by Django 5.2.1 on 2025-08-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boran_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproductos',
            name='sku',
            field=models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, to='boran_app.catalogo', to_field='sku', verbose_name='SKU'),
        ),
    ]
