# Generated by Django 5.2.1 on 2025-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boran_app', '0002_alter_entradaproductos_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
