# Generated by Django 5.2.7 on 2025-11-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boran_app', '0003_alter_ventas_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='credito',
            field=models.IntegerField(default=0, verbose_name='Crédito'),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='debito',
            field=models.IntegerField(default=0, verbose_name='Débito'),
        ),
    ]
