# Generated by Django 5.2.1 on 2025-08-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoRentable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('venta_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('utilidad_bruta_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('margen_bruto', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'productos_rentables',
            },
        ),
    ]
