# Generated by Django 5.2.1 on 2025-08-07 20:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boran_app', '0001_initial'),
        ('consult_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodegaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Tienda/Bodega')),
            ],
            options={
                'verbose_name': 'Tienda/Bodega',
                'verbose_name_plural': 'Tiendas/Bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EnviosATiendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, to='boran_app.catalogo', to_field='sku', verbose_name='SKU')),
                ('tienda_bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consult_app.bodegatienda', verbose_name='Tienda/Bodega')),
            ],
            options={
                'verbose_name': 'Envío a Tienda',
                'verbose_name_plural': 'Envíos a Tiendas',
                'db_table': 'envios_a_tiendas',
                'ordering': ['-fecha', 'tienda_bodega'],
            },
        ),
        migrations.CreateModel(
            name='InventarioInicialTiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, to='boran_app.catalogo', to_field='sku', verbose_name='SKU')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consult_app.bodegatienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Inventario Inicial Tienda',
                'verbose_name_plural': 'Inventarios Iniciales Tiendas',
                'db_table': 'inventario_inicial_tiendas',
                'ordering': ['-fecha', 'tienda'],
            },
        ),
    ]
