# Generated by Django 5.2.1 on 2025-08-07 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boran_app', '0001_initial'),
        ('consult_app', '0002_bodegatienda_enviosatiendas_inventarioinicialtiendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventarioTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad (±)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_tienda', to='boran_app.catalogo', to_field='sku', verbose_name='SKU')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='consult_app.bodegatienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Ajuste Inventario Tienda',
                'verbose_name_plural': 'Ajustes Inventario Tienda',
                'db_table': 'ajustes_inventario_tiendas',
                'ordering': ['-fecha', 'tienda', 'sku'],
                'indexes': [models.Index(fields=['tienda', 'sku', 'fecha'], name='idx_ajustes_tsf')],
            },
        ),
    ]
