# Generated by Django 5.2.1 on 2025-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_app', '0003_ajusteinventariotienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviosatiendas',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
